// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1sfSRrBWDCGD1EJuTwTec3x1q2dBwnt8',
    appId: '1:398335400491:web:aaf9ca59ff598d3131686e',
    messagingSenderId: '398335400491',
    projectId: 'tiktok-clone-d757d',
    authDomain: 'tiktok-clone-d757d.firebaseapp.com',
    storageBucket: 'tiktok-clone-d757d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3X5flvuq0YHLYL61oMD0FtFUG6rg5K_k',
    appId: '1:398335400491:android:ff8c49ac7a1a49d231686e',
    messagingSenderId: '398335400491',
    projectId: 'tiktok-clone-d757d',
    storageBucket: 'tiktok-clone-d757d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6aVYXKe2EDbYKdRt35QIaoD_u8UAomeQ',
    appId: '1:398335400491:ios:8696ae351e0928af31686e',
    messagingSenderId: '398335400491',
    projectId: 'tiktok-clone-d757d',
    storageBucket: 'tiktok-clone-d757d.firebasestorage.app',
    iosBundleId: 'com.example.tiktokClone',
  );
}
